### ISSUE TITLE
Some API responses are HTML

### ISSUE THREAD

**Issue by couchand** [adzerk/adzerk-api#12] opened 2014-10-31 13:38 UTC
When making certain API requests, the server responds with a generic HTML error page rather than a JSON error.  This makes reliably parsing the response for an error message hard.

In particular, if the server is unable to parse the dates, it will reply with this generic error page.  This is an acute problem since the API date format isn't documented.

**Comment by couchand** [comment] 2015-07-15 19:45
Hey, any chance you guys are making progress on this?  I'm still getting this sometimes on otherwise apparently valid API calls.

Returning HTML really doesn't help a person figure out what's going on.  Will you be fixing this any time soon?

**Comment by chrsm** [comment] 2015-08-03 17:34
This bites me too from time to time. Any update? :)

**Comment by karnowski** [comment] 2015-08-05 00:29
No update yet.  I'm terribly sorry.  However, I am very concerned about this, and we *are* fixing it.  

We have two "comb the API" projects in progress right now that are helping us find and fix the root issues.  We will then roll out a big API "tech debt payment" that will include lots of fixes at once.  

I'm hesitant to make lots of little changes, as it will affect many of our API users (who are already working around this) negatively.  We will announce the change relatively soon.  Sorry to ask you to wait, but thank you for your patience.  Big things coming soon!

**Comment by chrsm** [comment] 2015-08-05 17:44
All good.

Curious - I assume that in the event the HTML page is returned (vs an expected JSON response), we should just re-try whatever action that we were doing?

**Comment by couchand** [comment] 2015-08-12 02:15
@chrsm I've found that sometimes works, but other times the request is in fact flawed in some non-obvious way.  Retrying it might help determine which case you're in, though.

**Comment by chrsm** [comment] 2015-08-12 17:18
Thanks @couchand. We do attempt to work around this, but we have created duplicates of items previously and I'm not sure if it's due to another bug, or if these requests sometimes go through but don't return successfully.

**Comment by karnowski** [comment] 2020-12-11 22:02
This issue has been around a while, and we've made several, several deep-down changes to the API.  I'm pretty sure we've fixed this issue, and since there's no specific steps to reproduce I'm just going to close this issue.

**Closed by karnowski** 2020-12-11 22:02 UTC

**Comment by couchand** [comment] 2020-12-15 14:20
Congrats @karnowski!  It sure is a red-letter day when you can necro an issue that's been silent for five years with news that it's probably fixed.
